version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: splito_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-splito}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-splito_secret}
      POSTGRES_DB: ${POSTGRES_DB:-splito_db}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - splito_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-splito} -d ${POSTGRES_DB:-splito_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

# uncomment this when running locally on machine
  # redis:
  #   image: redis:7-alpine
  #   container_name: splito_redis
  #   ports:
  #     - "6379:6379"
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # api service is run locally with: uvicorn app.main:app --reload
  # Uncomment below only if you want to run everything inside Docker
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: splito_api
    env_file:
      - .env
    ports:
      - "0.0.0.0:8001:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./app:/app/app

volumes:
  splito_postgres_data: